# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import connect_pb2 as connect__pb2


class ConnectStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.persent = channel.unary_unary(
        '/Connect/persent',
        request_serializer=connect__pb2.Request.SerializeToString,
        response_deserializer=connect__pb2.ReplyInt.FromString,
        )


class ConnectServicer(object):
  """The greeting service definition.
  """

  def persent(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ConnectServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'persent': grpc.unary_unary_rpc_method_handler(
          servicer.persent,
          request_deserializer=connect__pb2.Request.FromString,
          response_serializer=connect__pb2.ReplyInt.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Connect', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
