# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connect.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='connect.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rconnect.proto\"3\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04unit\x18\x03 \x01(\t\"\x1a\n\x08ReplyInt\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1c\n\nReplyFloat\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\xa8\x01\n\x06System\x12\x1c\n\x03\x63pu\x12\x08.Request\x1a\t.ReplyInt\"\x00\x12\x1e\n\x03mem\x12\x08.Request\x1a\x0b.ReplyFloat\"\x00\x12\x1f\n\x04swap\x12\x08.Request\x1a\x0b.ReplyFloat\"\x00\x12\x1e\n\x03net\x12\x08.Request\x1a\x0b.ReplyFloat\"\x00\x12\x1f\n\x06uptime\x12\x08.Request\x1a\t.ReplyInt\"\x00\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='Request.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='Request.unit', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=68,
)


_REPLYINT = _descriptor.Descriptor(
  name='ReplyInt',
  full_name='ReplyInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ReplyInt.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=96,
)


_REPLYFLOAT = _descriptor.Descriptor(
  name='ReplyFloat',
  full_name='ReplyFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ReplyFloat.result', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['ReplyInt'] = _REPLYINT
DESCRIPTOR.message_types_by_name['ReplyFloat'] = _REPLYFLOAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'connect_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)

ReplyInt = _reflection.GeneratedProtocolMessageType('ReplyInt', (_message.Message,), dict(
  DESCRIPTOR = _REPLYINT,
  __module__ = 'connect_pb2'
  # @@protoc_insertion_point(class_scope:ReplyInt)
  ))
_sym_db.RegisterMessage(ReplyInt)

ReplyFloat = _reflection.GeneratedProtocolMessageType('ReplyFloat', (_message.Message,), dict(
  DESCRIPTOR = _REPLYFLOAT,
  __module__ = 'connect_pb2'
  # @@protoc_insertion_point(class_scope:ReplyFloat)
  ))
_sym_db.RegisterMessage(ReplyFloat)



_SYSTEM = _descriptor.ServiceDescriptor(
  name='System',
  full_name='System',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=129,
  serialized_end=297,
  methods=[
  _descriptor.MethodDescriptor(
    name='cpu',
    full_name='System.cpu',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLYINT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='mem',
    full_name='System.mem',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLYFLOAT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='swap',
    full_name='System.swap',
    index=2,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLYFLOAT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='net',
    full_name='System.net',
    index=3,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLYFLOAT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='uptime',
    full_name='System.uptime',
    index=4,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLYINT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYSTEM)

DESCRIPTOR.services_by_name['System'] = _SYSTEM

# @@protoc_insertion_point(module_scope)
